In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

from fastembed import (
    SparseTextEmbedding,
    TextEmbedding,
    LateInteractionTextEmbedding,
    ImageEmbedding,
)
from fastembed.rerank.cross_encoder import TextCrossEncoder

pd.set_option("display.max_colwidth", None)

## Supported Text Embedding Models

In [3]:
supported_models = (
    pd.DataFrame(TextEmbedding.list_supported_models())
    .sort_values("size_in_GB")
    .drop(columns=["sources", "model_file", "additional_files"])
    .reset_index(drop=True)
)
supported_models

,model,description,license,size_in_GB,dim,tasks
0,BAAI/bge-small-en-v1.5,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: not so necessary, 2023 year.",mit,0.067,384,{}
1,BAAI/bge-small-zh-v1.5,"Text embeddings, Unimodal (text), Chinese, 512 input tokens truncation, Prefixes for queries/documents: not so necessary, 2023 year.",mit,0.090,512,{}
2,snowflake/snowflake-arctic-embed-xs,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.090,384,{}
3,sentence-transformers/all-MiniLM-L6-v2,"Text embeddings, Unimodal (text), English, 256 input tokens truncation, Prefixes for queries/documents: not necessary, 2021 year.",apache-2.0,0.090,384,{}
4,jinaai/jina-embeddings-v2-small-en,"Text embeddings, Unimodal (text), English, 8192 input tokens truncation, Prefixes for queries/documents: not necessary, 2023 year.",apache-2.0,0.120,512,{}
5,BAAI/bge-small-en,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2023 year.",mit,0.130,384,{}
6,snowflake/snowflake-arctic-embed-s,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.130,384,{}
7,nomic-ai/nomic-embed-text-v1.5-Q,"Text embeddings, Multimodal (text, image), English, 8192 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.130,768,{}
8,BAAI/bge-base-en-v1.5,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: not so necessary, 2023 year.",mit,0.210,768,{}
9,sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2,"Text embeddings, Unimodal (text), Multilingual (~50 languages), 512 input tokens truncation, Prefixes for queries/documents: not necessary, 2019 year.",apache-2.0,0.220,384,{}
10,Qdrant/clip-ViT-B-32-text,"Text embeddings, Multimodal (text&image), English, 77 input tokens truncation, Prefixes for queries/documents: not necessary, 2021 year",mit,0.250,512,{}
11,BAAI/bge-base-en,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2023 year.",mit,0.420,768,{}
12,snowflake/snowflake-arctic-embed-m,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.430,768,{}
13,thenlper/gte-base,"General text embeddings, Unimodal (text), supports English only input text, 512 input tokens truncation, Prefixes for queries/documents: not necessary, 2024 year.",mit,0.440,768,{}
14,nomic-ai/nomic-embed-text-v1,"Text embeddings, Multimodal (text, image), English, 8192 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.520,768,{}
15,nomic-ai/nomic-embed-text-v1.5,"Text embeddings, Multimodal (text, image), English, 8192 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.520,768,{}
16,jinaai/jina-embeddings-v2-base-en,"Text embeddings, Unimodal (text), English, 8192 input tokens truncation, Prefixes for queries/documents: not necessary, 2023 year.",apache-2.0,0.520,768,{}
17,snowflake/snowflake-arctic-embed-m-long,"Text embeddings, Unimodal (text), English, 2048 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.540,768,{}
18,jinaai/jina-clip-v1,"Text embeddings, Multimodal (text&image), English, Prefixes for queries/documents: not necessary, 2024 year",apache-2.0,0.550,768,{}
19,jinaai/jina-embeddings-v2-base-de,"Text embeddings, Unimodal (text), Multilingual (German, English), 8192 input tokens truncation, Prefixes for queries/documents: not necessary, 2024 year.",apache-2.0,0.640,768,{}
20,jinaai/jina-embeddings-v2-base-code,"Text embeddings, Unimodal (text), Multilingual (English, 30 programming languages), 8192 input tokens truncation, Prefixes for queries/documents: not necessary, 2024 year.",apache-2.0,0.640,768,{}
21,jinaai/jina-embeddings-v2-base-zh,"Text embeddings, Unimodal (text), supports mixed Chinese-English input text, 8192 input tokens truncation, Prefixes for queries/documents: not necessary, 2024 year.",apache-2.0,0.640,768,{}
22,jinaai/jina-embeddings-v2-base-es,"Text embeddings, Unimodal (text), supports mixed Spanish-English input text, 8192 input tokens truncation, Prefixes for queries/documents: not necessary, 2024 year.",apache-2.0,0.640,768,{}
23,mixedbread-ai/mxbai-embed-large-v1,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,0.640,1024,{}
24,sentence-transformers/paraphrase-multilingual-mpnet-base-v2,"Text embeddings, Unimodal (text), Multilingual (~50 languages), 384 input tokens truncation, Prefixes for queries/documents: not necessary, 2021 year.",apache-2.0,1.000,768,{}
25,snowflake/snowflake-arctic-embed-l,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",apache-2.0,1.020,1024,{}
26,thenlper/gte-large,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: not necessary, 2023 year.",mit,1.200,1024,{}
27,BAAI/bge-large-en-v1.5,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: not so necessary, 2023 year.",mit,1.200,1024,{}
28,google/embeddinggemma-300m,"Text embeddings, Unimodal (text), multilingual, 2048 input tokens truncation, Prefixes for queries/documents: `task: search result | query: {content}` for query, `title: {title | 'none'} | text: {content}` for documents, 2025 year.",apache-2.0,1.240,768,{}
29,intfloat/multilingual-e5-large,"Text embeddings, Unimodal (text), Multilingual (~100 languages), 512 input tokens truncation, Prefixes for queries/documents: necessary, 2024 year.",mit,2.240,1024,{}
30,jinaai/jina-embeddings-v3,"Multi-task unimodal (text) embedding model, multi-lingual (~100), 1024 tokens truncation, and 8192 sequence length. Prefixes for queries/documents: not necessary, 2024 year.",cc-by-nc-4.0,2.290,1024,"{'retrieval.query': 0, 'retrieval.passage': 1, 'separation': 2, 'classification': 3, 'text-matching': 4}"

## Supported Sparse Text Embedding Models

In [4]:
(
    pd.DataFrame(SparseTextEmbedding.list_supported_models())
    .sort_values("size_in_GB")
    .drop(columns=["sources", "model_file", "additional_files"])
    .reset_index(drop=True)
)

,model,description,license,size_in_GB,requires_idf,vocab_size
0,Qdrant/bm25,BM25 as sparse embeddings meant to be used with Qdrant,apache-2.0,0.010,True,0
1,Qdrant/bm42-all-minilm-l6-v2-attentions,"Light sparse embedding model, which assigns an importance score to each token in the text",apache-2.0,0.090,True,30522
2,Qdrant/minicoil-v1,"Sparse embedding model, that resolves semantic meaning of the words, while keeping exact keyword match behavior. Based on jinaai/jina-embeddings-v2-small-en-tokens",apache-2.0,0.090,True,19125
3,prithivida/Splade_PP_en_v1,Independent Implementation of SPLADE++ Model for English.,apache-2.0,0.532,None,30522
4,prithvida/Splade_PP_en_v1,Independent Implementation of SPLADE++ Model for English.,apache-2.0,0.532,None,30522
5,opensearch-project/opensearch-neural-sparse-encoding-doc-v3-gte,"Inference-free SPLADE model. Documents are expanded with an ONNX encoder at index time, queries are encoded with a tokenizer and an IDF lookup table only, without any model inference.",apache-2.0,0.550,None,30522

## Supported Late Interaction Text Embedding Models

In [5]:
(
    pd.DataFrame(LateInteractionTextEmbedding.list_supported_models())
    .sort_values("size_in_GB")
    .drop(columns=["sources", "model_file"])
    .reset_index(drop=True)
)

,model,description,license,size_in_GB,additional_files,dim,tasks
0,answerdotai/answerai-colbert-small-v1,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, 2024 year",apache-2.0,0.13,[],96,{}
1,colbert-ir/colbertv2.0,"Text embeddings, Unimodal (text), English, 512 input tokens truncation, 2023 year",mit,0.44,[],128,{}
2,jinaai/jina-colbert-v2,"New model that expands capabilities of colbert-v1 with multilingual and context length of 8192, 2024 year",cc-by-nc-4.0,2.24,[onnx/model.onnx_data],128,{}

## Supported Image Embedding Models

In [6]:
(
    pd.DataFrame(ImageEmbedding.list_supported_models())
    .sort_values("size_in_GB")
    .drop(columns=["sources", "model_file"])
    .reset_index(drop=True)
)

,model,description,license,size_in_GB,additional_files,dim,tasks
0,Qdrant/resnet50-onnx,"Image embeddings, Unimodal (image), 2016 year",apache-2.0,0.10,[],2048,{}
1,nomic-ai/nomic-embed-vision-v1.5-Q,"Image embeddings, Multimodal (text&image), 2024 year",apache-2.0,0.10,[],768,{}
2,Qdrant/clip-ViT-B-32-vision,"Image embeddings, Multimodal (text&image), 2021 year",mit,0.34,[],512,{}
3,jinaai/jina-clip-v1,"Image embeddings, Multimodal (text&image), 2024 year",apache-2.0,0.34,[],768,{}
4,nomic-ai/nomic-embed-vision-v1.5,"Image embeddings, Multimodal (text&image), 2024 year",apache-2.0,0.37,[],768,{}
5,Qdrant/Unicom-ViT-B-32,"Image embeddings, Multimodal (text&image), 2023 year",apache-2.0,0.48,[],512,{}
6,Qdrant/Unicom-ViT-B-16,"Image embeddings (more detailed than Unicom-ViT-B-32), Multimodal (text&image), 2023 year",apache-2.0,0.82,[],768,{}

## Supported Rerank Cross Encoder Models

In [7]:
(
    pd.DataFrame(TextCrossEncoder.list_supported_models())
    .sort_values("size_in_GB")
    .drop(columns=["sources", "model_file"])
    .reset_index(drop=True)
)

,model,description,license,size_in_GB,additional_files
0,Xenova/ms-marco-MiniLM-L-6-v2,MiniLM-L-6-v2 model optimized for re-ranking tasks.,apache-2.0,0.08,[]
1,Xenova/ms-marco-MiniLM-L-12-v2,MiniLM-L-12-v2 model optimized for re-ranking tasks.,apache-2.0,0.12,[]
2,jinaai/jina-reranker-v1-tiny-en,Designed for blazing-fast re-ranking with 8K context length and fewer parameters than jina-reranker-v1-turbo-en.,apache-2.0,0.13,[]
3,jinaai/jina-reranker-v1-turbo-en,Designed for blazing-fast re-ranking with 8K context length.,apache-2.0,0.15,[]
4,BAAI/bge-reranker-base,BGE reranker base model for cross-encoder re-ranking.,mit,1.04,[]
5,jinaai/jina-reranker-v2-base-multilingual,A multi-lingual reranker model for cross-encoder re-ranking with 1K context length and sliding window,cc-by-nc-4.0,1.11,[]